// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCun-xoBuhcwsU1JydnzzZiCtGLCtgPwio',
    appId: '1:1046689193737:web:6c29753aef3992baa1fdd8',
    messagingSenderId: '1046689193737',
    projectId: 'cmsc23-todo-app-mdiguin-c4l',
    authDomain: 'cmsc23-todo-app-mdiguin-c4l.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-mdiguin-c4l.appspot.com',
    measurementId: 'G-GZZ23LH3M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABMTz2Qbr3uEDs6C5M21L3RCZFgTdU84U',
    appId: '1:1046689193737:android:aa3ab4a8e0601a8aa1fdd8',
    messagingSenderId: '1046689193737',
    projectId: 'cmsc23-todo-app-mdiguin-c4l',
    storageBucket: 'cmsc23-todo-app-mdiguin-c4l.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvBEAuCrTZOwM3h4mxs4XDt7E3P-zEaz4',
    appId: '1:1046689193737:ios:979034feba0b5440a1fdd8',
    messagingSenderId: '1046689193737',
    projectId: 'cmsc23-todo-app-mdiguin-c4l',
    storageBucket: 'cmsc23-todo-app-mdiguin-c4l.appspot.com',
    iosClientId: '1046689193737-l5gq780dkji7d0d51v7gtog91a9q4hj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvBEAuCrTZOwM3h4mxs4XDt7E3P-zEaz4',
    appId: '1:1046689193737:ios:979034feba0b5440a1fdd8',
    messagingSenderId: '1046689193737',
    projectId: 'cmsc23-todo-app-mdiguin-c4l',
    storageBucket: 'cmsc23-todo-app-mdiguin-c4l.appspot.com',
    iosClientId: '1046689193737-l5gq780dkji7d0d51v7gtog91a9q4hj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
